apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment 
spec:
  replicas: 3 
  selector:
    matchLabels:
      name: nginx-deployment
  template:
    metadata: 
      labels:
        name: nginx-deployment 
    spec:
      containers:
      - name: nginx-deployment
        image: nginx:1.7.9 
        ports:
        - containerPort: 80